# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-01 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0016_update_model_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_id',
            field=models.CharField(help_text='The CLIENT_ID given by MercadoPago.', max_length=16, verbose_name='client id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='secret_key',
            field=models.CharField(help_text='The CLIENT_SECRET given by MercadoPago.', max_length=32, verbose_name='secret key'),
        ),
    ]
