# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-01 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0017_account_app_id_secret_key_help_text'),
        ('mp', '0018_payment_mp_id_unique_false'),
    ]

    operations = [
    ]
