name: Checks

on: [push]

jobs:
  styles:
    runs-on: ubuntu-18.04
    name: Linting
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Install test dependencies
        run: pip install tox
      - name: Run flake8
        run: tox
        env:
          TOXENV: flake8
